### ISSUE TITLE
Vulnerable version of grunt-contrib-uglify

### ISSUE THREAD

**Issue by mvhirsch** [nikita-kit/nikita-kickstarter#10]
Nikita uses an vulnerable version of grunt-contrib-uglify, see https://zyan.scripts.mit.edu/blog/backdooring-js/ for more information.

https://github.com/nikita-kit/nikita-kickstarter/blob/master/package.json#L39

Please update soon!

**Comment by DracoBlue** [comment]
Fixed in https://github.com/nikita-kit/generator-nikita/pull/33

**Comment by DracoBlue** [comment]
And with 2565d6b7d7d533b97cc8934e80eca52758bb94da

**Comment by mvhirsch** [comment]
@DracoBlue Thank you!
